### ISSUE TITLE
simplify with date/time

### ISSUE THREAD

**Issue by matheuseduardo** [stefanocudini/gpx-simplify-optimizer#21] opened 2017-01-09 16:25 UTC
It's too far to be an "issue", just a suggestion (and a own need).

Is there a way to (calculate and) keep `time` of `trkpt`?

Have you thought about this possibility before?

In my case, in the file [runtastic_20150118_0848_Running.gpx.txt](https://github.com/stefanocudini/gpx-simplify-optimizer/files/693990/runtastic_20150118_0848_Running.gpx.txt) I have track from a run and I would like to simplify and keep date/time. Just a thought.

Thanks in advance.

**Comment by Wilkins** [comment] 2017-01-09 22:17
Hi @matheuseduardo,
Is this relates to #10 ?
How it is different ?

Enhancement and suggestions are welcome :-)

**Comment by Wilkins** [comment] 2017-03-17 22:10
Duplicate of #10 which is fixed. 

Issue fixed. But  http://labs.easyblog.it/maps/gpx-simplify-optimizer/ is not up to date from the github repository.

Otherwise, people can use the optimizer with this feature on my public copy : http://wilkins.fr/gpx/ 
NB: This is a working copy so things might get broken sometimes...

**Closed by Wilkins** 2017-03-17 22:10 UTC
Labels: duplicate
